language: python
python:  # Limiting this list to 5 will avoid job queuing
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

install:
  - pip install -U -e .
  - pip install -U setuptools pipenv
  - pipenv install --dev

script:
  - pipenv run py.test -v
  - pipenv run pylama
