language: python

matrix:
  include:
  - python: "3.5"
    env: PYRAMID_VERSION=1.5
  - python: "3.6"
    env: PYRAMID_VERSION=1.5
  - python: "3.6"
    env: PYRAMID_VERSION=1.9
  - python: "3.6"
    env: PYRAMID_VERSION=1.10.1
  - python: "3.7"
    env: PYRAMID_VERSION=1.10.1

install:
  - pip --disable-pip-version-check install -U setuptools pipenv
  - pipenv install --dev

script:
  - pipenv run mypy pyramid_bugsnag tests
  - pipenv run py.test -v
  - pipenv run pylama
