version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout

      - restore_cache:
          key: venv-{{ arch }}-{{ checksum "Pipfile" }}-{{ checksum "Pipfile.lock" }}
      - run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade setuptools
          pip install pipenv
          pipenv install --dev --system
      - save_cache:
          key: venv-{{ arch }}-{{ checksum "Pipfile" }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "venv"

      - run:
          name: linters
          command: |
            . venv/bin/activate
            pylama
      - run:
          name: tests
          command: |
            . venv/bin/activate
            py.test -v
